buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://plugins.gradle.org/m2/" }
    }
}
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'fabric-loom' version '1.3.8'
}

group = 'com.goodbird.cnpcgeckoaddon'
version = '1.20.1-1.0.0'

java {
    archivesBaseName = 'CNPC-Gecko-Addon-Fabric'
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}


loom {
    //accessWidenerPath = file("src/main/resources/customnpcs.accesswidener")
    mixin.defaultRefmapName = "cnpcgeckoaddon.refmap.json"
    sourceSets.main.java.srcDirs += 'src/api/java'
    runs {
        gameTest {
            server()
            vmArg "-Dfabric-api.gametest=1"
        }

        xplatDatagen {
            client()
            vmArg "-Dbotania.xplat_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=botania"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../Xplat/src/generated/resources")}"
        }

        fabricDatagen {
            client()
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=botania"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
        }

        configureEach {
            runDir "../run"
            ideConfigGenerated(true)
        }
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }


repositories {
    flatDir {
        dirs 'lib'
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.1:2023.09.03@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:0.15.6"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.1+1.20.1"

    modImplementation 'lib:CustomNPCs:1.20.1-GBPort-Unofficial-20240709'
    modImplementation "software.bernie.geckolib:geckolib-fabric-1.20.1:4.4.6"
    modImplementation "com.eliotlash.mclib:mclib:20"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "CNPC-Gecko-Addon",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
                "MixinConfigs": "mixins.cnpcgeckoaddon.json", // Конфигурации миксинов, через зяпятую если их несколько
                "FMLCorePluginContainsFMLMod": "true",  // Не забываем указать эти два флага,
                "ForceLoadAsMod": "true",               // чтобы Forge нормально загрузил и мод, и миксины
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
