buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://plugins.gradle.org/m2/" }
    }
}
// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

group = 'com.goodbird.cnpcgeckoaddon'
version = '1.21.1-1.0.0'

java {
    archivesBaseName = 'CNPC-Gecko-Addon-Fabric'
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}


loom {
    accessWidenerPath = file("src/main/resources/cnpcgeckoaddon.accesswidener")
    mixin.defaultRefmapName = "cnpcgeckoaddon.refmap.json"
    sourceSets.main.java.srcDirs += 'src/api/java'
    runs {
        gameTest {
            server()
            vmArg "-Dfabric-api.gametest=1"
        }

        xplatDatagen {
            client()
            vmArg "-Dbotania.xplat_datagen=1"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=botania"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../Xplat/src/generated/resources")}"
        }

        fabricDatagen {
            client()
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.modid=botania"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
        }

        configureEach {
            runDir "../run"
            ideConfigGenerated(true)
        }
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }


repositories {
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.net/"
    }
    flatDir {
        dirs 'lib'
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21:2024.07.28@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:0.16.5"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.105.0+1.21.1"

    modImplementation 'lib:CustomNPCs-1.21.1-GBPort-Unofficial-20250323'
    modImplementation "software.bernie.geckolib:geckolib-fabric-1.21.1:4.7.5.1"
    modImplementation "com.eliotlash.mclib:mclib:20"
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
