modLoader = "javafml"
loaderVersion = "[47,)"

license = "All Rights Reserved"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId = "cnpcgeckoaddon"
version = "1.20.1-1.0.0"
displayName = "CNPC-Gecko-Addon"

#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="Goodbird"

description = '''
Allows you to use geckolib models on your npcs
'''

[[dependencies.cnpcgeckoaddon]]
modId = "minecraft"
versionRange = "[1.20.1,1.21)"
mandatory = true
side = "BOTH"
ordering = "NONE"

[[dependencies.cnpcgeckoaddon]]
modId = "forge"
versionRange = "[47,)"
mandatory = true
side = "BOTH"
ordering = "NONE"