modLoader="javafml"
loaderVersion="[43,)"

issueTrackerURL="http://my.issue.tracker/" #optional

license="CC BY-NC"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="cnpcgeckoaddon" #mandatory
version="1.19.2-1.0.0" #mandatory
displayName="CNPC-Gecko-Addon" #mandatory
#updateJSONURL="" #optional
displayURL="" #optional
#logoFile="" #optional
#credits="" #optional
authors="Goodbird" #optional
description='''
A compatibility bridge between CustomNPCs and GeckoLib
    '''

[[dependencies.cnpcefaddon]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.cnpcefaddon]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"